version: '3'
services:
  waf-dashboard:
    build:
      context: .
      dockerfile: apache-modsec/Dockerfile.combined
    ports:
      - "8880:8880"   # Apache port
      - "8000:8000"   # Dashboard port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./apache-modsec/logs:/var/log/apache2
      - ./dashboard:/app
      - modsec-rules:/usr/share/modsecurity-crs/rules
    environment:
      - LOG_FILE_PATH=/var/log/apache2/modsec_audit.log
      - PYTHONUNBUFFERED=1

networks:
  waf-net:
    driver: bridge

volumes:
  modsec-rules: